language: pythons

python:
  - 2.7
  - 3.6

services:
  - mongodb
install: pip install -r requirements.txt

script: pytest --cov=./

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

after_success:
  - codecov

