version: 2
working_directory: ~/FootBotApi
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4  # primary container for the build jo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Runnning tests
          command: |
            . venv/bin/activate
            py.test -vv FootBotApi/test



